### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by jhpedemonte**

### CODE REVIEW

**Comment by parente** [comment]
Need to tag 0.8.0 in the branch, bump to 0.8.1-dev in the branch, and bump to 0.9.0-dev in master.

**Comment by jhpedemonte** [comment]
Yep, all done now!

**Comment by parente** [comment]
🎈 🏆 🍰 💯

**Comment by parente** [comment]
Looks like the CHANGELOG only went into the 0.8.0 branch. Master is behind on 0.7.0

https://github.com/jupyter-incubator/dashboards_server/blob/master/CHANGELOG.md.

Just cherry-pick that commit into master HEAD for now.

**Pull request merged**
