### PR TITLE
[Issue 150] Fix caching of notebook data

### LINKED ISSUE #150: Changes to redeployed of bundled dashboard do not appear in UI on refresh
Looks like we're now caching notebooks after first load somewhere server-side. Need to read from disk every time to account for redeploys.

Behavior used to be correct.

### PR DESCRIPTION
**Pull request by jhpedemonte**
Ensure that we're always storing/getting using same path
from request.

Fixes #150

### CODE REVIEW

**Comment by jhpedemonte** [comment]
@parente Try this.

**Comment by parente** [comment]
Aye aye! Trying!

**Comment by parente** [comment]
Nope. Same behavior as before. Redeploying with a markdown cell change shows the old markdown in the rendered dashboard. Both for bundled and unbundled dashboards.

**Comment by parente** [comment]
Those sneaky regexes! Much better.

Running integration tests here. If all green, will merge.

**Pull request merged**
