### PR TITLE
[issue: 79] Support for bundled dashboards

### PR DESCRIPTION
**Pull request by jhpedemonte**
Ref #79

### CODE REVIEW

**Comment by parente** [comment]
Started testing using https://github.com/jupyter-incubator/dashboards_bundlers/pull/21 which more easily links the notebook server from the bundlers project to the running dashboards server Docker `demo-container` and includes a really simple decl widgets notebook that uses `urth-core-bind` only.

Test matrix (will update):

| status | dashboards_bundlers | dashboards_server | comment |
|---|---|---|---|
| :+1:  | master | master | Bundler uploads `widget_binding.ipynb` file unzipped, the server renders it, and it functions properly because the server initializes its own copy of decl widgets on page load. |
| :+1: | master | PR #122 | Bundler uploads `widget_binding.ipynb` file, the server renders it, but the widget does not appear / function because the server does not init decl widgets for unbundled notebooks anymore. |
| :-1:  | PR #19 | PR #122 | Bundler (incorrectly) uploads `widget_binding.ipynb` file alone, not a zip file with the notebook and the widgets. As a result, the dashboard renders but does not function on the server|

/cc @nitind

**Comment by parente** [comment]
Tested again. We're misaligned on `static/` subfolder in zip from bundler vs no static subfolder expected here. We discussed off GitHub: we're going to fix the bundler in https://github.com/jupyter-incubator/dashboards_bundlers/pull/19. The functions will take a root_path param or equiv. The old bundlers will pass `static`, the new one for dashboard server will pass empty string or '.' or equiv.

**Comment by jhpedemonte** [comment]
OK, major updates landed and rebased to master. Both unit and integration tests are passing. Please test again if you have the chance.

**Comment by parente** [comment]
Will test again when the bundler update is in.

**Comment by parente** [comment]
Latest :+1: . Ready to :shipit: if you are.

**Comment by dalogsdon** [comment]
:+1:

**Pull request merged**
