### PR TITLE
[Issue 139] Remove Gridstack & bower

### PR DESCRIPTION
**Pull request by dalogsdon**
Required an upgrade to Gridstack 0.2.5 which also required:
* update Gridstack option names to camel case
* override a jquery-ui disabled style that Gridstack sets on cells

### CODE REVIEW

**Comment by dalogsdon** [comment]
resolves #39

**Comment by parente** [comment]
Do we need to (should we) update to 0.25 in the dashboard extension too?

**Comment by jhpedemonte** [comment]
@parente That's handled by this PR: https://github.com/jupyter-incubator/dashboards/pull/196

**Comment by jhpedemonte** [comment]
Code looks fine but haven't tested.

**Comment by parente** [comment]
@jhpedemonte In that dashboards PR, you mentioned there were some functional problems. I'd like to see those tested / addressed before upgrading here.

**Comment by parente** [comment]
(Hit submit too soon ...)

... if it matters that the other is 0.24 and this one is 0.25. If it doesn't matter, then nevermind.

**Comment by parente** [comment]
Decided to keep this WIP to tackle #139 in this same PR so that we're not upgrading bower then immediately removing it.

**Comment by dalogsdon** [comment]
Updated to remove Gridstack.

 This should resolve #139, #126, and #39 now.

**Comment by parente** [comment]
I'll give this a shot in the AM.

**Comment by parente** [comment]
All of the current demos work as expected. There will be merge conflicts with #136 but they're minor. You and @jhpedemonte can have a rock-paper-scissors battle about which goes in first. (I'll sit out and do the passport merge last. I doubt it conflicts anyway.)

**Comment by jhpedemonte** [comment]
Latest code seems fine to me.

**Comment by dalogsdon** [comment]
rebased

**Comment by parente** [comment]
:shipit:

**Pull request merged**
