### PR TITLE
[issue: 171] Use cookie session storage

### PR DESCRIPTION
**Pull request by jameslmartin**
Implements #171 to store session data using Express cookie-sessions

(c) Copyright IBM Corp. 2016

### CODE REVIEW

**Comment by dalogsdon** [comment]
Do we still need to be using `express-session` now that we are using `cookie-session`? I don't think I see any references to it anymore in app.js.

**Comment by parente** [comment]
If it's still in the package.json, yea we can remove it.

**Comment by dalogsdon** [comment]
It is in package.json and required in app.js with no references to it.

**Comment by parente** [comment]
@jameslmartin can you submit a follow-on PR?

**Pull request merged**
