### PR TITLE
[WIP] Added link to upload notebook response

### PR DESCRIPTION
**Pull request by dalogsdon**
This can be used in the dashboard bundler for redirecting to uploaded dashboard (PR incoming on that project).

Also cleaned up some upload code.

### CODE REVIEW

**Comment by parente** [comment]
Need to hold off on this until we release 0.5. (Monday probably.) And looks like there's a test failure in the meantime. (I didn't check Travis to see why.)

**Comment by dalogsdon** [comment]
Test has been fixed.

**Comment by dalogsdon** [comment]
This breaks uploading bundled dashboard zips. Will update to fix.

**Comment by dalogsdon** [comment]
Closing in favor of #213 which contains these changes

**Pull request closed without merging**
