### PR TITLE
[Issue 40] Update to jupyter-js-services 0.5

### PR DESCRIPTION
**Pull request by jhpedemonte**
Simple (non-ipywidgets) and declwidgets notebooks are all working.
jupyter-js-widgets needs to be updated (services-shim.js) for those
to work as well.

Ref #40

### CODE REVIEW

**Comment by jhpedemonte** [comment]
Currently pointing at my PR to update ipywidgets to use latest jupyter-js-widgets. Unfortunately, I'm now getting errors loading ipywidgets, generally about not being able to create a view for the model. Not sure why this is broken now.

**Comment by jhpedemonte** [comment]
Hmm, getting `slider is not a function` error when calling `$('<div').slider(...)` in **IntSliderView**. Will have to take a look at this on Monday.

**Comment by parente** [comment]
Enjoy your weekend. Pick it up Monday. :)

**Comment by jhpedemonte** [comment]
Fixed sliders issue -- needed to load full `jquery-ui` since `ipywidgets` requires it. With latest patch, the **web3** demo loads. But now I'm getting a ton of errors on **variable_inspector**!!  This never ends.

**Comment by jhpedemonte** [comment]
Issue with **variable_inspector** (and others) is fixed by [this ipywidgets change](https://github.com/ipython/ipywidgets/pull/383/files#r53712524). Will update SHA once that's in.

Now have issues where dropdown menus don't show, but display this error:

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`

**Comment by jhpedemonte** [comment]
Menu issue caused by ipywidgets code looking for DOM ID which only exists in Notebook ([comment](https://github.com/ipython/ipywidgets/pull/373/files#r53713194)).

**Comment by jhpedemonte** [comment]
Updated ipywidgets & declwidgets versions.

- Still having issues with ipywidgets dropdowns (i.e. *test_clear_output.ipynb*) -- but now it's a different error: `Uncaught TypeError: this.$dropbutton.dropdown is not a function` when clicking on the down arrow.
- Most declwidgets notebooks load fine, except for *decl-widgets.ipynb*. Get error `Uncaught TypeError: Cannot read property 'set' of undefined`.

**Comment by jhpedemonte** [comment]
OK, I think I've finally got this. Using latest ipywidgets commit and an updated branch of declwidgets, all test dashboards are now working.

Now to rebase and run tests.

**Comment by jhpedemonte** [comment]
@parente or @dalogsdon, I think this is ready for review.

**Comment by parente** [comment]
```
make clean
make build
make dev-install
```

I clicked through the majority of the notebooks. No surprises.

I'm opening an issue about cleaning up the `data/` dir and thinking about what would make better user-facing samples.

**Comment by parente** [comment]
Fixes issue #40.

**Pull request merged**
