### PR TITLE
Updates Jupyter dependencies to use 'jupyterlab' module

### LINKED ISSUE #259: Change to new location of jupyter-js-*
jupyter-js-ui and jupyter-js-notebook are now in one jupyterlab package. Need to update our deps and webpack config to pull in the pieces we need.

* https://gitter.im/jupyter/jupyterlab?at=5764031391d56ac9155c4ebf (and down)
* https://www.npmjs.com/package/jupyterlab
* https://github.com/jupyter/jupyterlab/blob/master/tutorial/repo.md

### PR DESCRIPTION
**Pull request by jhpedemonte**
Updates to use latest output-area APIs

Fixes #259

### CODE REVIEW

**Comment by jhpedemonte** [comment]
This works for most of our test/demo notebooks. However, some ipywidgets and declwidgets have comm errors. Not sure why.

**Comment by jhpedemonte** [comment]
@blink1073 @jasongrout: I'm updating to use `jupyterlab` module. As you can see in changelog, I had to also make edits due to API changes around `OutputAreaModel`, `OutputAreaWidget` and `RenderMime`.  Do these changes seem correct?

Most of our test notebooks are working, except I'm now seeing comm errors where I didn't previously (when using older `jupyter-js-ui` and `jupyter-js-notebook`). Any idea what changed to now cause these errors?

**Comment by blink1073** [comment]
Those changes seem sensible to me.  Can you give the actual comm errors?

**Comment by jhpedemonte** [comment]
@blink1073 Thanks for the quick review. The comm errors were actually a red herring -- turned out to be another required API change in our code.

---

Some declarative widgets are still broken. Getting the error `Uncaught (in promise) Error: Model not ready, cannot send message` for taxi demo.

**Comment by blink1073** [comment]
I don't *think* that message is coming from `jupyterlab` or `jupyter-js-services`, but a word search in the `ipywidgets` repo did not net anything either.

**Comment by jhpedemonte** [comment]
No, that error message is from Declarative Widgets, just not sure why. @lbustelo @deedubbu

**Comment by parente** [comment]
@jhpedemonte Incompatibility between decl widgets 0.6.x and the new ipywidgets 5.2.2?

**Comment by jhpedemonte** [comment]
Rebased to latest master, which includes fix for taxi_demo_grid notebook. Not seeing any further issues on test/demo notebooks.

**Comment by parente** [comment]
w00t! I'll give it a shot here and merge if I can reproduce everything properly.

**Comment by jhpedemonte** [comment]
I'm also looking at updating `services` dependency.

**Comment by parente** [comment]
Tried every demo notebook. No surprises. :shipit:

**Comment by blink1073** [comment]
:tada:

**Comment by parente** [comment]
Thanks for working through this @jhpedemonte (and the help @blink1073).

**Pull request merged**
